/* English Passport service worker — offline-first, versioned. Generated by the build step; do not edit the VERSION by hand. */
const VERSION = 'e393564ead';
const CACHE = 'ep-' + VERSION;
const SCOPE = self.registration.scope;
const PRECACHE = ['./', 'index.html', 'manifest.webmanifest', 'assets/progress.css', 'assets/progress.js', 'assets/english-passport-days.js', 'assets/daily-details-fa.js',
  'icons/icon-192.png', 'icons/icon-512.png', 'icons/icon-maskable-512.png',
  'icons/apple-touch-icon.png', 'icons/favicon-48.png'].map(p => new URL(p, SCOPE).href);
const INDEX = new URL('index.html', SCOPE).href;

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(PRECACHE.map(u => new Request(u, {cache: 'reload'}))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('ep-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/backup.json')) return; // always fresh from the network
  if (req.mode === 'navigate') {
    event.respondWith(caches.match(INDEX).then(hit => hit || fetch(req)));
    return;
  }
  event.respondWith(caches.match(req, {ignoreSearch: true}).then(hit => hit || fetch(req)));
});
